### ISSUE TITLE
A guide for best practices on testing

### ISSUE THREAD

**Issue by nayafia** [github/opensource.guide#194]
Tests are an important best practice in open source, yet many find it confusing. Older projects are still getting up to speed on tests, and new developers/contributors aren't always sure how to run and use tests. 

Might be worth creating a separate guide around testing:

## For projects
* What open source projects need to know about tests
* How to incorporate tests into an existing project
* Writing documentation about tests

## For contributors
* How open source contributors should use tests

## For both
* Tools for running tests, monitoring coverage, etc

**Comment by hzoo** [comment]
> Docs about test

There is usually some kind of convention to how tests are written, structured, etc that should be documented. Both linting/testing are usually described in the contributing.md (at least how to run them, and usually a command to run a subset of them). Usually you want to also be able to know how to run a debugger.

Each project may have a different structure on how you write tests: https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md#writing-tests. For Babel most of our tests are "fixture" based meaning that the test just compares the input/output code. More common tests are "exec" based because you are asserting a certain behavior (in Node this is as simple as using the `"assert"` module `assert.equal(2 + 2, 4)`.

> Test info

Tests are pretty vital to an open source project. It's common for projects to have coverage > 75% or even 100%. Many projects require PRs (especially bug fixes) to have a corresponding test case to catch for further regressions/issues. One of the harder parts of writing tests is if there aren't any infrastructure/existing tests to reference. This may require other libararies/tools to help with mocking certain behavior such as the CLI, filesystem, a network connection, user input, etc.

> contributors should use tests

Tests can also be an opportunity to learn about expected output/behavior. It's also a good area to start contributing to if there is missing coverage.

> Code coverage services

I know of 2: https://codecov.io/, https://coveralls.io/

Not sure we should recommend any specific tools/ideas since it won't apply across languages? For example for Node/JS the convention is to use `npm test` (also `npm t`) as the command to run tests.
