### ISSUE TITLE
Add link to the next step at the bottom of the page

### ISSUE THREAD

**Issue by benbalter** [github/opensource.guide#238]
When you scroll to the bottom of an article, you're left with somewhat of a dead end. You have to traverse back up to the home page, remember what article you just read, and then click the one after that. Instead, at the end of each article, it'd be awesome if there were a link to the "next step".

**Comment by benbalter** [comment]
> Would a "view other guides" call-to-action make sense to help it feel like less of a dead end? Another idea would be to have the navigation fixed so that the link back to the homepage is always present.

:+1: to either approach. Maybe browsing the site isn't the ideal use case. It could be that being linked to a specific doc, reading it, doing something is what we want to optimize for.

**Comment by MikeMcQuaid** [comment]
CC @nayafia to think about this when she's back.

**Comment by nayafia** [comment]
+1 to @sophshep's comments: since these are now standalone guides, we don't necessarily want to link to the "next" guide. But it would be good to give people something to do at the end.

> Would a "view other guides" call-to-action make sense to help it feel like less of a dead end? Another idea would be to have the navigation fixed so that the link back to the homepage is always present

I'm also :thumbsup: on either approach. "View related guides" would be ideal, but we don't currently have perfect content for all guides (ex. Legal doesn't really have similar guides).

Let's start with a simple link back to the homepage?

**Comment by mkermani144** [comment]
Any approaches on this issue?

**Comment by midhruvjaink** [comment]
any scope giving an articles navigation option either at the top of every page or making a column at the right?

**Comment by nayafia** [comment]
@mkermani144 @midhruvjaink this issue is still open, if someone would like to start by adding a link back to the homepage at the end of a guide.

I'd also be interested in seeing approaches to a fixed navigation with a link back to the homepage (if you do this, try starting with a quick mockup before doing work!).

**Comment by guptasaloni** [comment]
you can just make a button and write code to redirect it on the home page

**Comment by guptasaloni** [comment]
And if u are facing that much problem u can see the most popular website in that a link is there to redirect the home page and u can see the code by inspect it

**Comment by Nader-Zubaid** [comment]
nader79zubaid.wordpress.com

**Comment by nayafia** [comment]
Closing in favor of https://github.com/github/opensource.guide/issues/427. I wrote a fresher version so it's clearer what needs to be done.
