### ISSUE TITLE
Add: Print the Article option

### ISSUE THREAD

**Issue by midhruvjaink** [github/opensource.guide#370]
Adding the feature to Print the article or either download it as pdf.

**Comment by bkeepers** [comment]
Hey @midhruvjaink, thanks for the suggestion!

This isn't currently a high priority for us, but we would be happy to accept pull requests that:

- Add PDF versions as part of the process for generating ebooks #316 
- Improve the CSS styles for print formats

I'm going to close this issue since we're not actively looking for improvements to the print versions, but feel free to continue discussion or open a pull request.
