### ISSUE TITLE
Clarify how the DCO work

### ISSUE THREAD

**Issue by akosyakov** [github/opensource.guide#444]
It would be nice if the documentation covers how the DCO work, especially how to solve such cases: https://github.com/probot/dco/issues/37

**Comment by mlinksva** [comment]
Currently the DCO gets a one-sentence mention in https://opensource.guide/legal/#does-my-project-need-an-additional-contributor-agreement and the Guides don't provide detailed implementation help on anything. I [wish](https://github.com/github/opensource.guide/issues/50#issuecomment-241538924) there were better documentation for the DCO, but I don't think this project is the place to provide it.

probot/dco has more documentation than developercertificate.org which is [why](https://github.com/github/opensource.guide/pull/375) the Guide text links to the former. Maybe continue to add documentation there if you can get a solid answer.

I'm also tempted to delete "even simpler" from the Guide's mention of the DCO, because it's not simple to understand how it works.

**Comment by akosyakov** [comment]
Maybe it was "even simpler" for contributors to agree to it compare to the CLA.

**Comment by mlinksva** [comment]
Closing as detailed documentation on particular instruments is out of scope for this project.

**Comment by KRUSTH** [comment]
translation from brazil
