### ISSUE TITLE
"It's friday..." sentence is not included in translation-issue-template.

### ISSUE THREAD

**Issue by felixshai** [github/opensource.guide#473]
I notice that when visiting website on Friday.
There is a sentence pop up starting with "It's Friday! Invest a few hours..." at the index page.

1.   The sentence is not included in translation-issue-template.
2.   I push my translated version of `index.html` to my repository, it causes Jekyll fail with "unable to build page. Please try again later." I still trying to figure out how to fix it.

**Comment by mlinksva** [comment]
#450 added support for translating that string.

I'm not sure it makes sense to add to https://github.com/github/opensource.guide/blob/c7715ccc367c3636a3edbfbd8cfad5a36a6e934f/docs/templates/translation-issue-template.md because there's now no non-translatable text on the home page.

Could you point to he specific commit in your repo that you're getting that Jekyll failure with?

**Comment by felixshai** [comment]
In `github/opensource.guide` - `gh-pages` Branch
Turns out that sentence is now placed at `_data\locale\en-US.yml` which is included in translation-issue-template. 
My repo was not update to github's version. The sentence is still at '\index.html'.
I'm new to using git. I think I can try my best to merge github's version to my repo and save my already translated article at the same time. Any teaching to fulfill the task is welcome.
I think that bypass the Jekyll failure problem. This issue can be noted as closed.

**Comment by mlinksva** [comment]
https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/ might help. Feel free to ask if you have troubles.
