### ISSUE TITLE
"stale" issues

### ISSUE THREAD

**Issue by isomorphisms** [github/opensource.guide#583]
https://opensource.guide/metrics/

I don’t believe issues should be closed simply because time has elapsed. They should be dismissed, addressed, or marked as infeasible based on their own merits.

**Comment by lee-dohm** [comment]
Thanks for contributing.

I'm not sure what the expected action is here. We use Issues as work items to be completed, done, or otherwise laid to rest. All I see here is a statement of an opinion. While it is completely valid as an opinion, there isn't anything to be "done" with it. As such, I'm going to close this for now.

If I'm misunderstanding something, please let us know :+1:
